### ISSUE TITLE
RuntimeError:"_pickle.UnpicklingError: invalid load key, 'v'."

### ISSUE THREAD

**Issue by zongyunbo** [fourson/DeblurGAN-pytorch#3]
Hello! I have a pronlem when I run "python test.py --resume weights/WGAN_GP/checkpoint-epoch300.pth"or "python deblur_image.py --blurred data/blurred --deblurred data/sharp --resume weights/WGAN_GP/checkpoint-epoch300.pth" . It about "Traceback (most recent call last):
  File "deblur_image.py", line 59, in <module>
    main(args.blurred, args.deblurred, args.resume)
  File "deblur_image.py", line 12, in main
    checkpoint = torch.load(resume)
  File "/home/zongyb/.conda/envs/deblurGan/lib/python3.6/site-packages/torch/serialization.py", line 231, in load
    return _load(f, map_location, pickle_module)
  File "/home/zongyb/.conda/envs/deblurGan/lib/python3.6/site-packages/torch/serialization.py", line 369, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, 'v'"
"

**Comment by fourson** [comment]
when you git clone the repo, the file in model are not the correct one, there are too big to be download by git, there are replace by text file. You can either download them manually, on the website github just click on download, either using git-lfs to get the weights.
