### ISSUE TITLE
unrecognized arguments: weights\WGAN_GP

### ISSUE THREAD

**Issue by edemqs** [fourson/DeblurGAN-pytorch#7]
Hello. I try to run the program but I get an error. How can I solve that?

(base) C:\Users\EQUISPE\demo\DeblurGAN-pytorch-master>python deblur_image.py --blurred C:\Users\EQUISPE\demo\DeblurGAN-pytorch-master\prueba --deblurred C:\Users\EQUISPE\demo\DeblurGAN-pytorch-master\output --resume C:\Users\EQUISPE\demo\DeblurGAN-pytorch-master\checkpoints\pretrained weights\WGAN_GP
usage: deblur_image.py [-h] -b BLURRED -d DEBLURRED -r RESUME [--device DEVICE]

deblur_image.py: error: unrecognized arguments: weights\WGAN_GP

**Comment by fourson** [comment]
Please kindly note that in Windows the space (in "pretrained weights") must be escaped.
