### ISSUE TITLE
The problem of optimal weights for models

### ISSUE THREAD

**Issue by fyf12138** [fourson/DeblurGAN-pytorch#8]
Hello! May I ask if you can provide the best weights for the model trained on the GOPRO dataset? Due to my limited computing power, I would like to use your weight directly as I will not use it for commercial purposes.

**Comment by fourson** [comment]
The pre-trained weights are uploaded. However, what you want is "the best weights for the model trained on the GOPRO dataset", and I cannot make sure our weight is the best.
